name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Clone the repositories
          sudo git clone git@github.com:Lin-Jacob/TerpNotesFE.git /home/ubuntu/terpnotes/frontend
          sudo git clone git@github.com:olaniyisalami/TerpNotesBE.git /home/ubuntu/terpnotes/backend

          # Navigate to the frontend and build it
          sudo cd /home/ubuntu/terpnotes/frontend
          sudo npm install
          sudo npm run build

          # Navigate to the backend and set up
          sudo cd /home/ubuntu/terpnotes/backend
          sudo pip install -r requirements.txt

          # Run backend
          sudo pkill -f app.py || true
          sudo nohup python3 app.py &
        EOF
